# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'grid_geohash_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_grid_geohash_form(object):
    def setupUi(self, grid_geohash_form):
        grid_geohash_form.setObjectName("grid_geohash_form")
        grid_geohash_form.setWindowModality(QtCore.Qt.NonModal)
        grid_geohash_form.setEnabled(True)
        grid_geohash_form.resize(376, 165)
        grid_geohash_form.setMouseTracking(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(grid_geohash_form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.status = QtWidgets.QProgressBar(grid_geohash_form)
        self.status.setProperty("value", 24)
        self.status.setObjectName("status")
        self.gridLayout_2.addWidget(self.status, 4, 0, 1, 2)
        self.LblStatus = QtWidgets.QLabel(grid_geohash_form)
        self.LblStatus.setText("")
        self.LblStatus.setObjectName("LblStatus")
        self.gridLayout_2.addWidget(self.LblStatus, 3, 0, 1, 2)
        self.LinOutputFolder = QtWidgets.QLineEdit(grid_geohash_form)
        self.LinOutputFolder.setReadOnly(True)
        self.LinOutputFolder.setObjectName("LinOutputFolder")
        self.gridLayout_2.addWidget(self.LinOutputFolder, 2, 0, 1, 1)
        self.BtnOutputFolder = QtWidgets.QPushButton(grid_geohash_form)
        self.BtnOutputFolder.setObjectName("BtnOutputFolder")
        self.gridLayout_2.addWidget(self.BtnOutputFolder, 2, 1, 1, 1)
        self.Label = QtWidgets.QLabel(grid_geohash_form)
        self.Label.setObjectName("Label")
        self.gridLayout_2.addWidget(self.Label, 1, 0, 1, 2)
        self.spinPrecision = QtWidgets.QSpinBox(grid_geohash_form)
        self.spinPrecision.setMinimum(1)
        self.spinPrecision.setMaximum(30)
        self.spinPrecision.setObjectName("spinPrecision")
        self.gridLayout_2.addWidget(self.spinPrecision, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(grid_geohash_form)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.BtnApplyClose = QtWidgets.QDialogButtonBox(grid_geohash_form)
        self.BtnApplyClose.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Close)
        self.BtnApplyClose.setObjectName("BtnApplyClose")
        self.verticalLayout.addWidget(self.BtnApplyClose)

        self.retranslateUi(grid_geohash_form)
        self.BtnApplyClose.accepted.connect(grid_geohash_form.accept) # type: ignore
        self.BtnApplyClose.rejected.connect(grid_geohash_form.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(grid_geohash_form)

    def retranslateUi(self, grid_geohash_form):
        _translate = QtCore.QCoreApplication.translate
        grid_geohash_form.setWindowTitle(_translate("grid_geohash_form", "Geohash Grid Generator"))
        self.BtnOutputFolder.setText(_translate("grid_geohash_form", "..."))
        self.Label.setText(_translate("grid_geohash_form", "Select folder to save shapefile"))
        self.spinPrecision.setToolTip(_translate("grid_geohash_form", "Geohash Precision [1,30]"))
        self.label_2.setText(_translate("grid_geohash_form", "Precision"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    grid_geohash_form = QtWidgets.QDialog()
    ui = Ui_grid_geohash_form()
    ui.setupUi(grid_geohash_form)
    grid_geohash_form.show()
    sys.exit(app.exec_())
